# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_acount.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(625, 158)
        Dialog.setStyleSheet("background-color: white;")
        self.bank_name_header = QtWidgets.QLabel(Dialog)
        self.bank_name_header.setGeometry(QtCore.QRect(0, 0, 241, 36))
        self.bank_name_header.setStyleSheet("background-color: #e9ecef")
        self.bank_name_header.setAlignment(QtCore.Qt.AlignCenter)
        self.bank_name_header.setObjectName("bank_name_header")
        self.account_id_header = QtWidgets.QLabel(Dialog)
        self.account_id_header.setGeometry(QtCore.QRect(235, 0, 201, 36))
        self.account_id_header.setStyleSheet("background-color: #e9ecef")
        self.account_id_header.setAlignment(QtCore.Qt.AlignCenter)
        self.account_id_header.setObjectName("account_id_header")
        self.send_money_header = QtWidgets.QLabel(Dialog)
        self.send_money_header.setGeometry(QtCore.QRect(435, 0, 191, 36))
        self.send_money_header.setStyleSheet("background-color: #e9ecef")
        self.send_money_header.setAlignment(QtCore.Qt.AlignCenter)
        self.send_money_header.setObjectName("send_money_header")
        self.save_btn = QtWidgets.QPushButton(Dialog)
        self.save_btn.setGeometry(QtCore.QRect(155, 90, 116, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.save_btn.setObjectName("save_btn")
        self.close_btn = QtWidgets.QPushButton(Dialog)
        self.close_btn.setGeometry(QtCore.QRect(305, 90, 116, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.close_btn.setObjectName("close_btn")
        self.bank_name_input = QtWidgets.QLineEdit(Dialog)
        self.bank_name_input.setGeometry(QtCore.QRect(0, 35, 240, 31))
        self.bank_name_input.setStyleSheet("background-color: rgb(239, 239, 239, 130);\n"
"font: 13pt \"Lucida Bright\";")
        self.bank_name_input.setAlignment(QtCore.Qt.AlignCenter)
        self.bank_name_input.setObjectName("bank_name_input")
        self.account_id_input = QtWidgets.QLineEdit(Dialog)
        self.account_id_input.setGeometry(QtCore.QRect(239, 35, 197, 31))
        self.account_id_input.setStyleSheet("background-color: rgb(239, 239, 239, 130);\n"
"border: 1px solid gray;\n"
"font: 13pt \"Lucida Bright\";")
        self.account_id_input.setAlignment(QtCore.Qt.AlignCenter)
        self.account_id_input.setObjectName("account_id_input")
        self.line1 = QtWidgets.QLabel(Dialog)
        self.line1.setGeometry(QtCore.QRect(239, 0, 1, 35))
        self.line1.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.line1.setText("")
        self.line1.setObjectName("line1")
        self.line1_2 = QtWidgets.QLabel(Dialog)
        self.line1_2.setGeometry(QtCore.QRect(435, 0, 1, 35))
        self.line1_2.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.line1_2.setText("")
        self.line1_2.setObjectName("line1_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(435, 35, 191, 31))
        self.label.setStyleSheet("background-color: rgb(239, 239, 239, 130);\n"
"border: 1px solid gray;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.bank_name_header.raise_()
        self.save_btn.raise_()
        self.close_btn.raise_()
        self.send_money_header.raise_()
        self.account_id_header.raise_()
        self.account_id_input.raise_()
        self.bank_name_input.raise_()
        self.line1.raise_()
        self.line1_2.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.bank_name_header.setText(_translate("Dialog", "Bank Name"))
        self.account_id_header.setText(_translate("Dialog", "Account ID"))
        self.send_money_header.setText(_translate("Dialog", "Send Money"))
        self.save_btn.setText(_translate("Dialog", "SAVE"))
        self.close_btn.setText(_translate("Dialog", "CLOSE"))
        self.bank_name_input.setText(_translate("Dialog", "dadea"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
