# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'customer_main_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1197, 745)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.create_customer = QtWidgets.QPushButton(Form)
        self.create_customer.setGeometry(QtCore.QRect(40, 95, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_customer.sizePolicy().hasHeightForWidth())
        self.create_customer.setSizePolicy(sizePolicy)
        self.create_customer.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.create_customer.setObjectName("create_customer")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(505, -10, 241, 131))
        self.label.setStyleSheet("font: 28pt \"Lucida Bright\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(704, 185, 176, 31))
        self.label_3.setStyleSheet("font: 15pt \"Lucida Bright\";")
        self.label_3.setObjectName("label_3")
        self.list_deselect = QtWidgets.QLabel(Form)
        self.list_deselect.setGeometry(QtCore.QRect(1104, 185, 31, 31))
        self.list_deselect.setStyleSheet("font: 63 12pt \"Lucida Bright\";")
        self.list_deselect.setText("")
        self.list_deselect.setPixmap(QtGui.QPixmap("C:/Users/Daniel/Desktop/odoo/icon_lista.png"))
        self.list_deselect.setObjectName("list_deselect")
        self.kanban_deselect = QtWidgets.QLabel(Form)
        self.kanban_deselect.setGeometry(QtCore.QRect(1135, 185, 31, 31))
        self.kanban_deselect.setStyleSheet("font: 63 12pt \"Lucida Bright\";")
        self.kanban_deselect.setText("")
        self.kanban_deselect.setPixmap(QtGui.QPixmap("C:/Users/Daniel/Desktop/odoo/kanbank_ne_select.png"))
        self.kanban_deselect.setObjectName("kanban_deselect")
        self.kanban_select = QtWidgets.QLabel(Form)
        self.kanban_select.setGeometry(QtCore.QRect(1135, 185, 31, 31))
        self.kanban_select.setStyleSheet("font: 63 12pt \"Lucida Bright\";")
        self.kanban_select.setText("")
        self.kanban_select.setPixmap(QtGui.QPixmap("C:/Users/Daniel/Desktop/odoo/kanban_select.png"))
        self.kanban_select.setObjectName("kanban_select")
        self.list_select = QtWidgets.QLabel(Form)
        self.list_select.setGeometry(QtCore.QRect(1104, 185, 31, 31))
        self.list_select.setStyleSheet("font: 63 12pt \"Lucida Bright\";")
        self.list_select.setText("")
        self.list_select.setPixmap(QtGui.QPixmap("C:/Users/Daniel/Desktop/odoo/list_select.png"))
        self.list_select.setScaledContents(True)
        self.list_select.setObjectName("list_select")
        self.antet_color = QtWidgets.QLabel(Form)
        self.antet_color.setGeometry(QtCore.QRect(0, -15, 1226, 781))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antet_color.sizePolicy().hasHeightForWidth())
        self.antet_color.setSizePolicy(sizePolicy)
        self.antet_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.antet_color.setText("")
        self.antet_color.setObjectName("antet_color")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(915, 700, 251, 26))
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"border: 1px solid ;\n"
"border-top-color:  rgba(0, 0, 0, 75);\n"
"border-bottom-color:  rgba(0, 0, 0, 75);\n"
"border-left-color: rgba(0, 0, 0, 75);\n"
"border-right-color: rgba(255, 255, 255, 200);")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.page = QtWidgets.QLabel(Form)
        self.page.setGeometry(QtCore.QRect(1025, 705, 51, 16))
        self.page.setStyleSheet("color: rgb(255, 255, 255);")
        self.page.setAlignment(QtCore.Qt.AlignCenter)
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(33, 225, 1140, 471))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.previous_page_text = QtWidgets.QLabel(Form)
        self.previous_page_text.setGeometry(QtCore.QRect(915, 700, 111, 26))
        self.previous_page_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.previous_page_text.setAlignment(QtCore.Qt.AlignCenter)
        self.previous_page_text.setObjectName("previous_page_text")
        self.next_page_text = QtWidgets.QLabel(Form)
        self.next_page_text.setGeometry(QtCore.QRect(1075, 700, 91, 26))
        self.next_page_text.setStyleSheet("color: rgb(255, 255, 255);")
        self.next_page_text.setAlignment(QtCore.Qt.AlignCenter)
        self.next_page_text.setObjectName("next_page_text")
        self.filter_input = QtWidgets.QLineEdit(Form)
        self.filter_input.setGeometry(QtCore.QRect(879, 190, 186, 21))
        self.filter_input.setObjectName("filter_input")
        self.create_customer_2 = QtWidgets.QPushButton(Form)
        self.create_customer_2.setGeometry(QtCore.QRect(1045, 105, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_customer_2.sizePolicy().hasHeightForWidth())
        self.create_customer_2.setSizePolicy(sizePolicy)
        self.create_customer_2.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.create_customer_2.setObjectName("create_customer_2")
        self.antet_color.raise_()
        self.create_customer.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.list_deselect.raise_()
        self.kanban_deselect.raise_()
        self.kanban_select.raise_()
        self.list_select.raise_()
        self.label_6.raise_()
        self.page.raise_()
        self.frame.raise_()
        self.previous_page_text.raise_()
        self.next_page_text.raise_()
        self.filter_input.raise_()
        self.create_customer_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_customer.setText(_translate("Form", "CREATE"))
        self.label.setText(_translate("Form", "Costumers"))
        self.label_3.setText(_translate("Form", "Serach customer"))
        self.page.setText(_translate("Form", "10/10"))
        self.previous_page_text.setText(_translate("Form", "Previous Page"))
        self.next_page_text.setText(_translate("Form", "Next Page  "))
        self.create_customer_2.setText(_translate("Form", "CLOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
