# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sales_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1197, 745)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.create_customer = QtWidgets.QPushButton(Form)
        self.create_customer.setGeometry(QtCore.QRect(40, 50, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_customer.sizePolicy().hasHeightForWidth())
        self.create_customer.setSizePolicy(sizePolicy)
        self.create_customer.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.create_customer.setObjectName("create_customer")
        self.lb_title = QtWidgets.QLabel(Form)
        self.lb_title.setGeometry(QtCore.QRect(550, 25, 46, 31))
        self.lb_title.setStyleSheet("font: 63 14pt \"Lucida Bright\";")
        self.lb_title.setObjectName("lb_title")
        self.lb_filter = QtWidgets.QLabel(Form)
        self.lb_filter.setGeometry(QtCore.QRect(865, 90, 51, 31))
        self.lb_filter.setStyleSheet("font: 63 12pt \"Lucida Bright\";")
        self.lb_filter.setObjectName("lb_filter")
        self.antet_color = QtWidgets.QLabel(Form)
        self.antet_color.setGeometry(QtCore.QRect(-15, -15, 1226, 781))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antet_color.sizePolicy().hasHeightForWidth())
        self.antet_color.setSizePolicy(sizePolicy)
        self.antet_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.antet_color.setText("")
        self.antet_color.setObjectName("antet_color")
        self.sales_view_layout = QtWidgets.QFrame(Form)
        self.sales_view_layout.setGeometry(QtCore.QRect(33, 145, 1140, 551))
        self.sales_view_layout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sales_view_layout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sales_view_layout.setObjectName("sales_view_layout")
        self.antet_color.raise_()
        self.create_customer.raise_()
        self.lb_title.raise_()
        self.lb_filter.raise_()
        self.sales_view_layout.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_customer.setText(_translate("Form", "NEW"))
        self.lb_title.setText(_translate("Form", "Sales"))
        self.lb_filter.setText(_translate("Form", "Filter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
