# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sales_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(841, 691)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.create_sale_btn = QtWidgets.QPushButton(Form)
        self.create_sale_btn.setGeometry(QtCore.QRect(40, 80, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_sale_btn.sizePolicy().hasHeightForWidth())
        self.create_sale_btn.setSizePolicy(sizePolicy)
        self.create_sale_btn.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.create_sale_btn.setObjectName("create_sale_btn")
        self.lb_title = QtWidgets.QLabel(Form)
        self.lb_title.setGeometry(QtCore.QRect(360, 25, 101, 41))
        self.lb_title.setStyleSheet("font: 28pt \"Lucida Bright\";")
        self.lb_title.setObjectName("lb_title")
        self.lb_filter = QtWidgets.QLabel(Form)
        self.lb_filter.setGeometry(QtCore.QRect(485, 185, 121, 31))
        self.lb_filter.setStyleSheet("font: 15pt \"Lucida Bright\";")
        self.lb_filter.setObjectName("lb_filter")
        self.antet_color = QtWidgets.QLabel(Form)
        self.antet_color.setGeometry(QtCore.QRect(-30, -25, 1226, 781))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.antet_color.sizePolicy().hasHeightForWidth())
        self.antet_color.setSizePolicy(sizePolicy)
        self.antet_color.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.antet_color.setText("")
        self.antet_color.setObjectName("antet_color")
        self.sales_view_layout = QtWidgets.QFrame(Form)
        self.sales_view_layout.setGeometry(QtCore.QRect(30, 240, 786, 426))
        self.sales_view_layout.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sales_view_layout.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sales_view_layout.setObjectName("sales_view_layout")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(615, 190, 196, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.create_sale_btn_2 = QtWidgets.QPushButton(Form)
        self.create_sale_btn_2.setGeometry(QtCore.QRect(690, 80, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.create_sale_btn_2.sizePolicy().hasHeightForWidth())
        self.create_sale_btn_2.setSizePolicy(sizePolicy)
        self.create_sale_btn_2.setStyleSheet("background-color: rgb(174, 139, 137);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.create_sale_btn_2.setObjectName("create_sale_btn_2")
        self.antet_color.raise_()
        self.create_sale_btn.raise_()
        self.lb_title.raise_()
        self.lb_filter.raise_()
        self.sales_view_layout.raise_()
        self.lineEdit.raise_()
        self.create_sale_btn_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.create_sale_btn.setText(_translate("Form", "NEW"))
        self.lb_title.setText(_translate("Form", "Sales"))
        self.lb_filter.setText(_translate("Form", "Search sale"))
        self.create_sale_btn_2.setText(_translate("Form", "CLOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
